name: Run Test Script Every 5 Minutes

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Run test script
      run: python test_hello.py
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Check if there are changes to commit
        if git diff --quiet HEAD -- execution_log.csv; then
          echo "No changes to commit"
          exit 0
        fi
        
        # Get current timestamp for commit message
        TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
        PROCESS_STATUS="✅ Process Complete"
        
        git add execution_log.csv
        git commit -m "🚀 Automated execution log update

${PROCESS_STATUS} - ${TIMESTAMP}
- Script executed successfully
- CSV updated with latest timestamp
- Git action status: completed

[AUTO-COMMIT]" || exit 0
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
