name: Simple Test Workflow

on:
  workflow_dispatch:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Run test script
      run: python test_hello.py
      
    - name: Simple commit test
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add execution_log.csv
        git diff --staged --quiet || git commit -m "Simple test commit from GitHub Actions"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}